# Generated by Django 4.1.2 on 2022-10-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accoutnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
