# Generated by Django 4.1.2 on 2022-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_p_price_shopcart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='amount',
            field=models.FloatField(default=1.0),
        ),
    ]
