# Generated by Django 4.1.2 on 2022-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_payment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
