# Generated by Django 4.1.2 on 2022-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='item_carted',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='amount',
            field=models.FloatField(),
        ),
    ]
