# Generated by Django 4.1.3 on 2022-11-10 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0008_shopcart_item_carted_alter_shopcart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
